spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Manas@65
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: PRODUCT-SERVICE

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-with-registry: true
server:
  port: 8082